name = "VKPony"
author = "Fauli1221"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e62db32785de72b10d52ac297002cb427eba3f2cfb8a737a1b514a339cc795d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
