name = "VKPony"
author = "Fauli1221"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0b6f01c60767ffd3ae85aa68b07c1136a3f9dbbac14b62d7e6431c3586d263d"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
