name = "VKPony"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03dbb00acad0a2632a5c75535186d4b75f4d7be8f938edd02702fe5c71f1d6fd"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
